import './globals.css'
import localFont from 'next/font/local'

const inter = localFont({ 
  src: './Inter-VariableFont_slnt,wght.ttf',
  variable: '--font-inter', 
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>{children}</body>
    </html>
  )
}
